#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0

#define LV_DPI_DEF 200

#define LV_USE_PERF_MONITOR 0
#define LV_USE_MEM_MONITOR 0

#define LV_USE_STDLIB_MALLOC LV_STDLIB_STD
#define LV_USE_STDLIB_STRING LV_STDLIB_STD
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_STD

#define LV_USE_OBJ 1
#define LV_USE_SCREEN 1

#define LV_USE_BUTTON 1
#define LV_USE_LABEL 1
#define LV_USE_SLIDER 1
#define LV_USE_SWITCH 1
#define LV_USE_TEXTAREA 1
#define LV_USE_IMAGE 1

#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_22 1

#define LV_FONT_DEFAULT &lv_font_montserrat_16

#define LV_USE_FONT_COMPRESSED 0

#define LV_USE_THEME_SIMPLE 1

#define LV_USE_DRAW_SW 1
#define LV_USE_DRAW_SW_ARC 1
#define LV_USE_DRAW_SW_BLEND 1
#define LV_USE_DRAW_SW_LINE 1
#define LV_USE_DRAW_SW_TRIANGLE 0
#define LV_USE_DRAW_SW_IMAGE 1
#define LV_USE_DRAW_SW_BOX_SHADOW 0
#define LV_USE_DRAW_SW_MASK 0
#define LV_USE_DRAW_SW_TRANSFORM 0
#define LV_USE_DRAW_SW_GRADIENT 0
#define LV_USE_DRAW_SW_LAYER 0
#define LV_USE_DRAW_SW_STRIDE_ALIGN 1

#define LV_MEM_SIZE (32 * 1024)
#define LV_MEM_ATTR_ATTRIBUTE __attribute__((aligned(32)))

#define LV_USE_LOG 0

#define LV_USE_OS LV_OS_FREERTOS

#endif